version: 2.1

jobs:
  lint-app-microservices:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
  build-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker container - microservices
          command: |
            echo "--------- The images - Building ------------"
            
            docker build -t todoapp-frontend ./../
            docker tag todoapp-frontend thanhtt9900/todoapp-frontend:latest

            echo " ------- login in to hub--------"

            docker login -u "$DOCKER_USERNAME" -p $DOCKERHUB_PASSWORD

            echo "-------------- Pushing images to dockerhub-------"
            
            docker push thanhtt9900/todoapp-frontend:latest
workflows:
  default:
    jobs:
      - lint-app-frontend
      - build-docker:
          requires: [lint-app-frontend]